# Finds the include files necessary for compilation
message(STATUS "Detecting Delta3D")
find_path (DELTA3D_INCLUDE_DIR dtActors/gamemeshactor.h
    HINTS
	$ENV{DELTA_INC}
    $ENV{DELTA_ROOT}/include
    $ENV{DELTA_ROOT}/inc
    $ENV{DELTA_ROOT}
    $ENV{DELTA_ROOT}/ext/include
    $ENV{DELTA_ROOT}/ext/inc
    $ENV{DELTA_ROOT}/ext
)
mark_as_advanced (DELTA3D_INCLUDE_DIR)

macro (FIND_DELTA3D_LIBRARY MYLIBRARY MYLIBRARYNAME)
    # Finds the library files necessary for compilation
    find_library (${MYLIBRARY}
        NAMES ${MYLIBRARYNAME}
        HINTS
        $ENV{DELTA_LIB}
        $ENV{DELTA_ROOT}/lib
        $ENV{DELTA_ROOT}/lib64
        $ENV{DELTA_ROOT}
    )
    mark_as_advanced (${MYLIBRARY})
endmacro(FIND_DELTA3D_LIBRARY MYLIBRARY MYLIBRARYNAME)

if (TC_BUILD_WITH_RELEASE)
	# Finds all Delta3D release libraries
	FIND_DELTA3D_LIBRARY (DELTA3D_ABC_LIBRARY dtABC)
	FIND_DELTA3D_LIBRARY (DELTA3D_ACTORS_LIBRARY dtActors)
	FIND_DELTA3D_LIBRARY (DELTA3D_AI_LIBRARY dtAI)
	FIND_DELTA3D_LIBRARY (DELTA3D_ANIM_LIBRARY dtAnim)
	FIND_DELTA3D_LIBRARY (DELTA3D_CORE_LIBRARY dtCore)
	FIND_DELTA3D_LIBRARY (DELTA3D_DIRECTOR_LIBRARY dtDirector)
	FIND_DELTA3D_LIBRARY (DELTA3D_DIRECTORANIMNODES_LIBRARY dtDirectorAnimNodes)
	FIND_DELTA3D_LIBRARY (DELTA3D_DIRECTORYAUDIONODES_LIBRARY dtDirectorAudioNodes)
	FIND_DELTA3D_LIBRARY (DELTA3D_DIRECTORGUINODES_LIBRARY dtDirectorGUINodes)
	FIND_DELTA3D_LIBRARY (DELTA3D_DIRECTORNODES_LIBRARY dtDirectorNodes)
	FIND_DELTA3D_LIBRARY (DELTA3D_DIRECTORQT_LIBRARY dtDirectorQt)
	FIND_DELTA3D_LIBRARY (DELTA3D_GAME_LIBRARY dtGame)
	FIND_DELTA3D_LIBRARY (DELTA3D_GUI_LIBRARY dtGUI)
	FIND_DELTA3D_LIBRARY (DELTA3D_INPUTPLIB_LIBRARY dtInputPLIB)
	FIND_DELTA3D_LIBRARY (DELTA3D_INSPECTORQT_LIBRARY dtInspectorQt)
	FIND_DELTA3D_LIBRARY (DELTA3D_LMS_LIBRARY dtLMS)
	FIND_DELTA3D_LIBRARY (DELTA3D_NET_LIBRARY dtNet)
	FIND_DELTA3D_LIBRARY (DELTA3D_NETGM_LIBRARY dtNetGM)
	FIND_DELTA3D_LIBRARY (DELTA3D_PHYSICS_LIBRARY dtPhysics)
	FIND_DELTA3D_LIBRARY (DELTA3D_QT_LIBRARY dtQt)
	FIND_DELTA3D_LIBRARY (DELTA3D_RENDER_LIBRARY dtRender)
	FIND_DELTA3D_LIBRARY (DELTA3D_TERRAIN_LIBRARY dtTerrain)
	FIND_DELTA3D_LIBRARY (DELTA3D_UTIL_LIBRARY dtUtil)
	FIND_DELTA3D_LIBRARY (DELTA3D_VOXEL_LIBRARY dtVoxel)
endif (TC_BUILD_WITH_RELEASE)

if (TC_BUILD_WITH_DEBUG)
	# Finds all Delta3D debug libraries
	FIND_DELTA3D_LIBRARY (DELTA3D_ABC_LIBRARY_DEBUG dtABCd)
	FIND_DELTA3D_LIBRARY (DELTA3D_ACTORS_LIBRARY_DEBUG dtActorsd)
	FIND_DELTA3D_LIBRARY (DELTA3D_AI_LIBRARY_DEBUG dtAId)
	FIND_DELTA3D_LIBRARY (DELTA3D_ANIM_LIBRARY_DEBUG dtAnimd)
	FIND_DELTA3D_LIBRARY (DELTA3D_CORE_LIBRARY_DEBUG dtCored)
	FIND_DELTA3D_LIBRARY (DELTA3D_DIRECTOR_LIBRARY_DEBUG dtDirectord)
	FIND_DELTA3D_LIBRARY (DELTA3D_DIRECTORANIMNODES_LIBRARY_DEBUG dtDirectorAnimNodesd)
	FIND_DELTA3D_LIBRARY (DELTA3D_DIRECTORYAUDIONODES_LIBRARY_DEBUG dtDirectorAudioNodesd)
	FIND_DELTA3D_LIBRARY (DELTA3D_DIRECTORGUINODES_LIBRARY_DEBUG dtDirectorGUINodesd)
	FIND_DELTA3D_LIBRARY (DELTA3D_DIRECTORNODES_LIBRARY_DEBUG dtDirectorNodesd)
	FIND_DELTA3D_LIBRARY (DELTA3D_DIRECTORQT_LIBRARY_DEBUG dtDirectorQtd)
	FIND_DELTA3D_LIBRARY (DELTA3D_GAME_LIBRARY_DEBUG dtGamed)
	FIND_DELTA3D_LIBRARY (DELTA3D_GUI_LIBRARY_DEBUG dtGUId)
	FIND_DELTA3D_LIBRARY (DELTA3D_INPUTPLIB_LIBRARY_DEBUG dtInputPLIBd)
	FIND_DELTA3D_LIBRARY (DELTA3D_INSPECTORQT_LIBRARY_DEBUG dtInspectorQtd)
	FIND_DELTA3D_LIBRARY (DELTA3D_LMS_LIBRARY_DEBUG dtLMSd)
	FIND_DELTA3D_LIBRARY (DELTA3D_NET_LIBRARY_DEBUG dtNetd)
	FIND_DELTA3D_LIBRARY (DELTA3D_NETGM_LIBRARY_DEBUG dtNetGMd)
	FIND_DELTA3D_LIBRARY (DELTA3D_PHYSICS_LIBRARY_DEBUG dtPhysicsd)
	FIND_DELTA3D_LIBRARY (DELTA3D_QT_LIBRARY_DEBUG dtQtd)
	FIND_DELTA3D_LIBRARY (DELTA3D_RENDER_LIBRARY_DEBUG dtRenderd)
	FIND_DELTA3D_LIBRARY (DELTA3D_TERRAIN_LIBRARY_DEBUG dtTerraind)
	FIND_DELTA3D_LIBRARY (DELTA3D_UTIL_LIBRARY_DEBUG dtUtild)
	FIND_DELTA3D_LIBRARY (DELTA3D_VOXEL_LIBRARY_DEBUG dtVoxeld)
endif (TC_BUILD_WITH_DEBUG)

set (DELTA3D_FOUND "NO")
if (DELTA3D_CORE_LIBRARY AND DELTA3D_INCLUDE_DIR)
    set (DELTA3D_FOUND "YES")
    message(STATUS "Delta3D Found!")
else (DELTA3D_CORE_LIBRARY AND DELTA3D_INCLUDE_DIR)    
    message("Delta3D Not Found!")
endif (DELTA3D_CORE_LIBRARY AND DELTA3D_INCLUDE_DIR)
