# Platform specific definitions
IF (WIN32)
    MESSAGE(STATUS "Configuring for Windows")

	IF (MSVC_IDE)
		OPTION (TR_BUILD_WITH_MP "Enables the /MP multi-processor compiler option for Visual Studio 2005 and above" ON)		
		MARK_AS_ADVANCED (TR_BUILD_WITH_MP)
		IF (TR_BUILD_WITH_MP)
			SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MP")
		ENDIF (TR_BUILD_WITH_MP)
		
		OPTION (TR_BUILD_WITH_STRICT "Enables the Option STRICT for VS compiler" ON)
		MARK_AS_ADVANCED (TR_BUILD_WITH_STRICT)
		IF (TR_BUILD_WITH_STRICT)
			SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DSTRICT")
		ENDIF (TR_BUILD_WITH_STRICT)
		
		OPTION (TR_BUILD_WITH_LEAN_AND_MEAN "Enables the option LEAN_AND_MEAN for VS compiler, to speed up compilation" ON)
		MARK_AS_ADVANCED (TR_BUILD_WITH_LEAN_AND_MEAN)
		IF (TR_BUILD_WITH_LEAN_AND_MEAN)
			SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DWIN32_LEAN_AND_MEAN")
		ENDIF (TR_BUILD_WITH_LEAN_AND_MEAN)
	ENDIF (MSVC_IDE)

ENDIF (WIN32)

# Common global definitions
OPTION (CMAKE_USE_RELATIVE_PATHS "Uses relative paths in project settings" ON)

SET (TR_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/include)
SET (TR_SOURCE_DIR ${PROJECT_SOURCE_DIR}/src)

SET (EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/bin)
SET (LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/lib)

SET (OUTPUT_BINDIR ${PROJECT_BINARY_DIR}/BIN)
MAKE_DIRECTORY (${OUTPUT_BINDIR})
SET (EXECUTABLE_OUTPUT_PATH ${OUTPUT_BINDIR})

SET (OUTPUT_LIBDIR ${PROJECT_BINARY_DIR}/LIB)
MAKE_DIRECTORY (${OUTPUT_LIBDIR})
SET (LIBRARY_OUTPUT_PATH ${OUTPUT_LIBDIR})

SET (CMAKE_ARCHIVE_OUTPUT_DIRECTORY  ${OUTPUT_LIBDIR} CACHE PATH "build directory")
SET (CMAKE_RUNTIME_OUTPUT_DIRECTORY  ${OUTPUT_BINDIR} CACHE PATH "build directory")
IF (MSVC_IDE)
	SET (CMAKE_LIBRARY_OUTPUT_DIRECTORY ${OUTPUT_BINDIR} CACHE PATH "build directory")
ELSE (MSVC_IDE)
	SET (CMAKE_LIBRARY_OUTPUT_DIRECTORY ${OUTPUT_LIBDIR} CACHE PATH "build directory")
ENDIF (MSVC_IDE)

# For each configuration (Debug, Release, MinSizeRel... and/or anything the
# user chooses)
FOREACH (CONF ${CMAKE_CONFIGURATION_TYPES})
	# Go uppercase (DEBUG, RELEASE...)
	STRING (TOUPPER "${CONF}" CONF)
	SET ("CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CONF}" "${OUTPUT_LIBDIR}")
	SET ("CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CONF}" "${OUTPUT_BINDIR}")
	IF (MSVC_IDE)
		SET ("CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CONF}" "${OUTPUT_BINDIR}")
	ELSE ()
	    SET ("CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CONF}" "${OUTPUT_LIBDIR}")
	ENDIF ()
ENDFOREACH ()

# Expose CMAKE_INCLUDE_PATH and CMAKE_LIBARY_PATH to the GUI so users
# may set these values without needing to manipulate the environment.
SET (CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} CACHE STRING "You may add additional search paths here. Use ; to separate multiple paths.")
SET (CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} CACHE STRING "You may add additional search paths here. Use ; to separate multiple paths.")
SET (CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} CACHE STRING "You may add additional search paths here. Use ; to separate multiple paths.")
